version: '2'
services:
  # db:
  #   image: mysql:latest
  web:
    container_name: notebook
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    # depends_on:
    #   - db